import type { Content } from "./types";

const en: Content = {
  meta: {
    title: "LOOM — AI-Powered HR, Woven Across the Universe of Work",
    description:
      "LOOM unites Human Resources and Artificial Intelligence into one intelligent ecosystem — automating the repetitive, surfacing the meaningful, and connecting every thread of your workforce.",
    ogTitle: "LOOM — AI-Powered HR Management",
    ogDescription:
      "The AI-powered HR platform where human expertise and large language models work as one thread.",
  },
  nav: {
    links: [
      { href: "#features", label: "Platform" },
      { href: "#ai", label: "AI Assistant" },
      { href: "#why", label: "Why LOOM" },
      { href: "#pricing", label: "Pricing" },
      { href: "#faq", label: "FAQ" },
    ],
    cta: "Request a demo",
    menuAria: "Menu",
  },
  hero: {
    badge: "New",
    pillPre: "Conversational HR copilot powered by ",
    pillBold: "LLMs",
    headline: ["HR, woven", "across the", "universe of work."],
    sub: "LOOM unites Human Resources and Artificial Intelligence into one intelligent ecosystem — automating the repetitive, surfacing the meaningful, and connecting every thread of your workforce.",
    primaryCta: "Request a demo",
    secondaryCta: "Meet the AI assistant",
    trust: ["No credit card", "SOC 2 & GDPR ready", "Setup in days"],
    floatA: { k: "Onboarding", v: "Automated ✦" },
    floatB: { k: "Retention", v: "+18.4%" },
  },
  features: {
    eyebrow: "The full suite",
    heading: ["Eleven modules.", "One woven constellation."],
    lead: "Each piece of the employee experience, intelligently connected — so nothing falls through the cracks.",
    items: [
      { icon: "people", title: "Employee Management", desc: "A living directory, org charts and profiles that stay current automatically." },
      { icon: "recruit", title: "Recruitment", desc: "Source, track and collaborate on candidates with an AI-assisted pipeline." },
      { icon: "onboard", title: "Smart Onboarding", desc: "Personalized, automated onboarding journeys that run end to end." },
      { icon: "leave", title: "Leave Management", desc: "Self-serve requests, balances and approvals — no spreadsheets." },
      { icon: "attendance", title: "Attendance Tracking", desc: "Accurate time, shifts and presence across remote and on-site teams." },
      { icon: "payroll", title: "Payroll", desc: "Run accurate, compliant payroll with everything connected in one place." },
      { icon: "perf", title: "Performance Evaluation", desc: "Fair, data-informed reviews, goals and continuous feedback loops." },
      { icon: "learn", title: "Learning Management", desc: "Build skills with courses, paths and AI-recommended growth." },
      { icon: "analytics", title: "Analytics Dashboard", desc: "Real-time people metrics that turn data into clear decisions." },
      { icon: "workflow", title: "Workflow Automation", desc: "Trigger approvals, reminders and tasks across teams automatically." },
      { icon: "docs", title: "Document Management", desc: "Generate, sign and store every HR document securely." },
    ],
  },
  ai: {
    eyebrow: "LOOM Copilot",
    heading: ["An HR expert that", "never sleeps."],
    lead: "Powered by large language models, the LOOM assistant understands your policies, your data and your people — and acts on them in plain conversation.",
    capabilities: [
      "Answers any HR question instantly",
      "Generates contracts & HR documents",
      "Writes job descriptions in seconds",
      "Summarizes meetings & 1:1s",
      "Analyzes employee & team data",
      "Recommends next-best actions",
      "Evaluates performance fairly",
      "Automates repetitive workflows",
    ],
  },
  chat: {
    name: "LOOM Copilot",
    status: "online · LLM-powered",
    inputPlaceholder: "Ask anything about your people…",
    script: [
      { who: "user", text: "Draft a job description for a Senior Product Designer, remote in EU." },
      { who: "bot", text: "Done ✦ I've drafted a full JD with responsibilities, requirements and a salary band benchmarked to your market. Want me to post it to your careers page?", pill: "Generated in 2.4s" },
      { who: "user", text: "Also, who's at risk of churn on the engineering team?" },
      { who: "bot", text: "Three engineers show rising attrition signals based on engagement, tenure and 1:1 sentiment. I'd recommend a check-in with each — shall I draft talking points?", pill: "Analysis · 1,284 employees" },
    ],
  },
  why: {
    eyebrow: "Why LOOM",
    heading: ["Built for the way", "modern teams actually work."],
    items: [
      { title: "Productivity", desc: "Free your HR team from busywork so they can focus on people, not paperwork." },
      { title: "Automation", desc: "Repetitive workflows run themselves — approvals, reminders, documents and more." },
      { title: "Employee experience", desc: "A delightful self-serve portal and AI copilot your whole team will actually use." },
      { title: "Smarter decisions", desc: "Predictive analytics surface risks and opportunities before they happen." },
      { title: "Security & trust", desc: "Enterprise-grade encryption, SSO, audit logs and SOC 2 / GDPR readiness." },
      { title: "Scalability", desc: "From 20 to 20,000 employees — LOOM grows with you, AI-first by design." },
    ],
  },
  stats: [
    { count: 92, suffix: "%", decimals: 0, label: "Less time on HR admin" },
    { count: 3.4, suffix: "x", decimals: 1, label: "Faster onboarding" },
    { count: 18, suffix: "%", decimals: 0, label: "Higher retention" },
    { count: 24, suffix: "/7", decimals: 0, label: "AI copilot availability" },
  ],
  timeline: {
    eyebrow: "Employee lifecycle",
    heading: "Every thread, from hello to farewell.",
    lead: "LOOM follows each employee through their whole journey — and quietly handles the work at every step.",
    steps: [
      { icon: "recruit", tag: "HIRE", title: "Recruit", desc: "AI-assisted sourcing and structured interviews." },
      { icon: "onboard", tag: "START", title: "Onboard", desc: "Automated, personalized first-day journeys." },
      { icon: "perf", tag: "GROW", title: "Develop", desc: "Goals, feedback and learning paths." },
      { icon: "analytics", tag: "ENGAGE", title: "Retain", desc: "Pulse surveys and attrition signals." },
      { icon: "payroll", tag: "REWARD", title: "Reward", desc: "Payroll, benefits and recognition." },
      { icon: "docs", tag: "MOVE ON", title: "Offboard", desc: "Smooth, compliant transitions." },
    ],
  },
  testimonials: {
    eyebrow: "Loved by people teams",
    heading: "What HR leaders say about LOOM.",
    items: [
      { initials: "EM", color: "#7C3AED", textColor: "#fff", quote: "LOOM gave our 12-person HR team the leverage of 40. The AI copilot answers 80% of employee questions before they ever reach us.", name: "Elena Moreau", role: "VP People · Northwind" },
      { initials: "RC", color: "#2DD4BF", textColor: "#fff", quote: "Onboarding used to take two weeks of coordination. Now it's a single automated thread that runs itself. It feels like magic.", name: "Raj Chauhan", role: "Head of HR · Vertex" },
      { initials: "AB", color: "#FBBF24", textColor: "#3a2600", quote: "The analytics caught an attrition risk in one team weeks early. We acted, and kept three brilliant engineers. That paid for LOOM many times over.", name: "Amara Bello", role: "CHRO · Lumen" },
    ],
  },
  pricing: {
    eyebrow: "Pricing",
    heading: ["Simple plans that scale", "with your team."],
    lead: "Per employee, per month. No hidden fees. Cancel anytime.",
    plans: [
      {
        tier: "Starter",
        amount: "$6",
        unit: "/employee/mo",
        desc: "For growing teams putting HR on autopilot.",
        features: [
          "Employee management & directory",
          "Leave & attendance tracking",
          "Smart onboarding flows",
          "Basic AI copilot",
        ],
        cta: "Start free trial",
        ctaClass: "btn-glass",
      },
      {
        tier: "Growth",
        amount: "$12",
        unit: "/employee/mo",
        desc: "For companies scaling people operations with AI.",
        features: [
          "Everything in Starter",
          "Full LLM copilot & document generation",
          "Payroll & performance evaluation",
          "Advanced analytics & workflows",
          "Learning management",
        ],
        cta: "Request a demo",
        ctaClass: "btn-primary",
        featured: true,
        badge: "Most popular",
      },
      {
        tier: "Enterprise",
        amount: "Custom",
        desc: "For global organizations with advanced needs.",
        features: [
          "Everything in Growth",
          "SSO, SCIM & advanced security",
          "Custom AI models & data residency",
          "Dedicated success manager",
        ],
        cta: "Talk to sales",
        ctaClass: "btn-glass",
      },
    ],
  },
  faq: {
    eyebrow: "FAQ",
    heading: "Questions, answered.",
    items: [
      { q: "How does the LOOM AI copilot work?", a: "The copilot is built on large language models that securely understand your company policies, documents and people data. It answers questions, drafts HR documents, summarizes meetings and recommends actions — all in natural conversation, with your data never used to train public models." },
      { q: "How long does it take to get started?", a: "Most teams are live within days. LOOM imports your existing employee data, and our smart onboarding flows configure the core modules automatically. Enterprise rollouts with custom integrations typically take 2–4 weeks." },
      { q: "Is my employee data secure?", a: "Yes. LOOM uses enterprise-grade encryption in transit and at rest, role-based access controls, SSO, audit logging, and is SOC 2 and GDPR ready. You control data residency on Enterprise plans." },
      { q: "Can LOOM replace our current HR tools?", a: "LOOM consolidates employee management, recruitment, onboarding, leave, attendance, payroll, performance, learning, analytics, workflows and documents into one platform — replacing most point solutions while integrating with the tools you keep." },
      { q: "Do you integrate with our existing stack?", a: "LOOM connects with Slack, Google Workspace, Microsoft 365, common payroll providers, ATS tools and more via native integrations and an open API." },
      { q: "What does pricing look like for larger teams?", a: "Growth is billed per employee per month. For organizations over 500 employees we offer custom Enterprise pricing with volume discounts, dedicated support and advanced security — talk to our team for a quote." },
    ],
  },
  forms: {
    eyebrow: "Get started",
    heading: ["Let's weave LOOM", "into your team."],
    lead: "Tell us a little about your company and we'll tailor a walkthrough — or just drop us a line. A real human (backed by AI, of course) replies within one business day.",
    points: [
      { title: "Personalized 20-min demo", desc: "See LOOM and the AI copilot on your real use cases." },
      { title: "Custom ROI estimate", desc: "We'll model the hours and cost LOOM saves your team." },
      { title: "No pressure, no spam", desc: "Just helpful answers about whether LOOM fits." },
    ],
    email: "hello@loom.hr",
    phone: "+1 (800) 566-6000",
    tabs: { demo: "Request a demo", contact: "Contact sales" },
    demoForm: {
      firstName: "First name",
      lastName: "Last name",
      workEmail: "Work email",
      company: "Company",
      companySize: "Company size",
      companySizeOptions: ["1–50", "51–200", "201–500", "501–1,000", "1,000+"],
      role: "Role",
      roleOptions: ["HR / People", "Founder / CEO", "Operations", "IT / Security", "Other"],
      whatToSee: "What would you like to see?",
      whatToSeePlaceholder: "e.g. AI onboarding, payroll, analytics…",
      submit: "Book my demo",
      consentPre: "By submitting, you agree to LOOM's ",
      consentLink: "Privacy Policy",
      consentPost: ". We'll never share your data.",
      placeholders: { firstName: "Maya", lastName: "Anders", email: "maya@company.com", company: "Company name" },
    },
    contactForm: {
      fullName: "Full name",
      workEmail: "Work email",
      topic: "Topic",
      topicOptions: ["Enterprise pricing", "Security & compliance", "Integrations", "Partnerships", "Something else"],
      howCanWeHelp: "How can we help?",
      howCanWeHelpPlaceholder: "Tell us what you're looking for…",
      submit: "Send message",
      consent: "We typically reply within one business day.",
      placeholders: { fullName: "Maya Anders", email: "maya@company.com" },
    },
    success: {
      title: "Thank you — you're all set.",
      text: "We've received your request. A LOOM specialist will reach out within one business day.",
    },
  },
  cta: {
    heading: ["Ready to weave AI", "into your people team?"],
    text: "Join the companies building a smarter, more human workplace with LOOM. See it live in a 20-minute demo.",
    primary: "Request a demo",
    secondary: "Start free trial",
  },
  footer: {
    description: "The AI-powered HR platform where human expertise and large language models work as one thread.",
    columns: [
      { header: "Platform", links: [{ label: "Features", href: "#features" }, { label: "AI Copilot", href: "#ai" }, { label: "Pricing", href: "#pricing" }, { label: "Lifecycle", href: "#lifecycle" }] },
      { header: "Company", links: [{ label: "About", href: "#" }, { label: "Careers", href: "#" }, { label: "Customers", href: "#" }, { label: "Blog", href: "#" }] },
      { header: "Resources", links: [{ label: "Help center", href: "#faq" }, { label: "Security", href: "#" }, { label: "Privacy", href: "#" }, { label: "Status", href: "#" }] },
    ],
    copyright: "© 2026 LOOM Technologies. All rights reserved.",
  },
  showcase: {
    eyebrow: "One platform",
    heading: ["Mission control for", "your entire workforce."],
    lead: "From the first interview to the farewell, LOOM keeps every record, workflow and conversation woven together — on any device.",
    points: [
      { title: "Live employee directory", desc: "Org charts, profiles and documents that update themselves." },
      { title: "Self-serve for everyone", desc: "Employees request leave, update details and find answers without a ticket." },
      { title: "Workflows on autopilot", desc: "Trigger approvals, e-signatures and reminders across teams instantly." },
      { title: "Mobile-first by design", desc: "Approve, review and chat with the AI copilot from your pocket." },
    ],
    cta: "Explore the platform",
    phone: {
      greeting: "Hi Maya 👋",
      dayLabel: "Your day",
      approvalsTag: "3 APPROVALS",
      approvalsText: "Awaiting your review",
      paydayTag: "PAYDAY",
      paydayText: "In 4 days",
      askAi: "Ask the AI copilot…",
    },
  },
  dashboardMock: {
    url: "app.loom.hr / dashboard",
    nav: ["Dashboard", "People", "Payroll", "Analytics", "AI Copilot"],
    greeting: "Good morning, Maya 👋",
    quarter: "This quarter ▾",
    kpis: [
      { label: "Headcount", value: "1,284", trend: "▲ 4.1% MoM" },
      { label: "eNPS", value: "72", trend: "▲ 9 pts" },
      { label: "Open roles", value: "37", trend: "▼ 6 vs last wk" },
    ],
    hiringVelocity: "Hiring velocity",
    timeOffRequests: "Time-off requests",
    people: [
      { initials: "AK", color: "#7C3AED", name: "Aria Khan", sub: "Vacation · 3d", badge: "Approved", badgeClass: "green" },
      { initials: "JL", color: "#2DD4BF", name: "Jon Lee", sub: "Sick · 1d", badge: "Approved", badgeClass: "green" },
      { initials: "RP", color: "#FBBF24", textColor: "#3a2600", name: "Ravi Patel", sub: "Parental · 12w", badge: "Pending", badgeClass: "amber" },
    ],
  },
  langSwitcher: { fr: "FR", en: "EN" },
};

export default en;
