import type { Content } from "./types";

const fr: Content = {
  meta: {
    title: "LOOM — Les RH augmentées par l'IA, tissées à travers l'univers du travail",
    description:
      "LOOM réunit les Ressources Humaines et l'Intelligence Artificielle en un seul écosystème intelligent — automatisant le répétitif, révélant l'essentiel, et connectant chaque fil de vos équipes.",
    ogTitle: "LOOM — Gestion RH augmentée par l'IA",
    ogDescription:
      "La plateforme RH augmentée par l'IA où l'expertise humaine et les grands modèles de langage ne font plus qu'un.",
  },
  nav: {
    links: [
      { href: "#features", label: "Plateforme" },
      { href: "#ai", label: "Assistant IA" },
      { href: "#why", label: "Pourquoi LOOM" },
      { href: "#pricing", label: "Tarifs" },
      { href: "#faq", label: "FAQ" },
    ],
    cta: "Demander une démo",
    menuAria: "Menu",
  },
  hero: {
    badge: "Nouveau",
    pillPre: "Copilote RH conversationnel propulsé par des ",
    pillBold: "LLM",
    headline: ["Les RH, tissées", "à travers", "l'univers du travail."],
    sub: "LOOM réunit les Ressources Humaines et l'Intelligence Artificielle en un seul écosystème intelligent — automatisant le répétitif, révélant l'essentiel, et connectant chaque fil de vos équipes.",
    primaryCta: "Demander une démo",
    secondaryCta: "Découvrir l'assistant IA",
    trust: ["Sans carte bancaire", "Conforme SOC 2 & RGPD", "Mise en place en quelques jours"],
    floatA: { k: "Intégration", v: "Automatisée ✦" },
    floatB: { k: "Rétention", v: "+18,4%" },
  },
  features: {
    eyebrow: "La suite complète",
    heading: ["Onze modules.", "Une seule constellation tissée."],
    lead: "Chaque facette de l'expérience collaborateur, connectée intelligemment — pour que rien ne passe entre les mailles.",
    items: [
      { icon: "people", title: "Gestion des employés", desc: "Un annuaire vivant, des organigrammes et des profils qui restent à jour automatiquement." },
      { icon: "recruit", title: "Recrutement", desc: "Sourcez, suivez et collaborez sur vos candidats avec un pipeline assisté par l'IA." },
      { icon: "onboard", title: "Intégration intelligente", desc: "Des parcours d'intégration personnalisés et automatisés, de bout en bout." },
      { icon: "leave", title: "Gestion des congés", desc: "Demandes, soldes et validations en libre-service — fini les tableurs." },
      { icon: "attendance", title: "Suivi de présence", desc: "Temps de travail, plannings et présence précis, sur site comme à distance." },
      { icon: "payroll", title: "Paie", desc: "Une paie précise et conforme, avec tout connecté au même endroit." },
      { icon: "perf", title: "Évaluation de la performance", desc: "Des entretiens équitables et data-driven, des objectifs et un feedback continu." },
      { icon: "learn", title: "Gestion de la formation", desc: "Développez les compétences avec des parcours et des recommandations pilotées par l'IA." },
      { icon: "analytics", title: "Tableau de bord analytique", desc: "Des indicateurs RH en temps réel qui transforment la donnée en décisions claires." },
      { icon: "workflow", title: "Automatisation des workflows", desc: "Déclenchez validations, rappels et tâches entre équipes automatiquement." },
      { icon: "docs", title: "Gestion documentaire", desc: "Générez, signez et archivez chaque document RH en toute sécurité." },
    ],
  },
  ai: {
    eyebrow: "Copilote LOOM",
    heading: ["Un expert RH qui", "ne dort jamais."],
    lead: "Propulsé par de grands modèles de langage, l'assistant LOOM comprend vos politiques, vos données et vos équipes — et agit en langage naturel.",
    capabilities: [
      "Répond instantanément à toute question RH",
      "Génère contrats et documents RH",
      "Rédige des fiches de poste en quelques secondes",
      "Résume réunions et entretiens individuels",
      "Analyse les données collaborateurs et équipes",
      "Recommande les meilleures actions à mener",
      "Évalue la performance en toute équité",
      "Automatise les workflows répétitifs",
    ],
  },
  chat: {
    name: "Copilote LOOM",
    status: "en ligne · propulsé par LLM",
    inputPlaceholder: "Posez n'importe quelle question sur vos équipes…",
    script: [
      { who: "user", text: "Rédige une fiche de poste pour un Senior Product Designer, en remote en Europe." },
      { who: "bot", text: "C'est fait ✦ J'ai rédigé une fiche complète avec responsabilités, prérequis et une fourchette de salaire benchmarkée sur votre marché. Je la publie sur votre page carrières ?", pill: "Généré en 2,4s" },
      { who: "user", text: "Autre chose : qui risque de partir dans l'équipe ingénierie ?" },
      { who: "bot", text: "Trois ingénieurs montrent des signaux d'attrition croissants, basés sur l'engagement, l'ancienneté et le ressenti en entretien individuel. Je recommande un point avec chacun — je prépare les sujets à aborder ?", pill: "Analyse · 1 284 employés" },
    ],
  },
  why: {
    eyebrow: "Pourquoi LOOM",
    heading: ["Conçu pour la façon dont", "les équipes modernes travaillent vraiment."],
    items: [
      { title: "Productivité", desc: "Libérez votre équipe RH des tâches répétitives pour qu'elle se concentre sur les personnes, pas la paperasse." },
      { title: "Automatisation", desc: "Les workflows répétitifs tournent seuls — validations, rappels, documents et bien plus." },
      { title: "Expérience collaborateur", desc: "Un portail en libre-service agréable et un copilote IA que toute l'équipe utilisera vraiment." },
      { title: "Décisions plus intelligentes", desc: "L'analytique prédictive révèle risques et opportunités avant qu'ils ne surviennent." },
      { title: "Sécurité & confiance", desc: "Chiffrement de niveau entreprise, SSO, journaux d'audit et conformité SOC 2 / RGPD." },
      { title: "Scalabilité", desc: "De 20 à 20 000 employés — LOOM grandit avec vous, pensé IA dès le départ." },
    ],
  },
  stats: [
    { count: 92, suffix: "%", decimals: 0, label: "de temps administratif RH en moins" },
    { count: 3.4, suffix: "x", decimals: 1, label: "plus rapide pour intégrer" },
    { count: 18, suffix: "%", decimals: 0, label: "de rétention en plus" },
    { count: 24, suffix: "/7", decimals: 0, label: "disponibilité du copilote IA" },
  ],
  timeline: {
    eyebrow: "Cycle de vie collaborateur",
    heading: "Chaque fil, du premier bonjour à l'au revoir.",
    lead: "LOOM accompagne chaque collaborateur tout au long de son parcours — et gère discrètement le travail à chaque étape.",
    steps: [
      { icon: "recruit", tag: "RECRUTER", title: "Recruter", desc: "Sourcing assisté par l'IA et entretiens structurés." },
      { icon: "onboard", tag: "DÉMARRER", title: "Intégrer", desc: "Des parcours de premier jour automatisés et personnalisés." },
      { icon: "perf", tag: "GRANDIR", title: "Développer", desc: "Objectifs, feedback et parcours de formation." },
      { icon: "analytics", tag: "ENGAGER", title: "Fidéliser", desc: "Sondages ponctuels et signaux d'attrition." },
      { icon: "payroll", tag: "RÉCOMPENSER", title: "Récompenser", desc: "Paie, avantages et reconnaissance." },
      { icon: "docs", tag: "PASSER LE RELAIS", title: "Offboarder", desc: "Des transitions fluides et conformes." },
    ],
  },
  testimonials: {
    eyebrow: "Plébiscité par les équipes RH",
    heading: "Ce que les dirigeants RH disent de LOOM.",
    items: [
      { initials: "EM", color: "#7C3AED", textColor: "#fff", quote: "LOOM a donné à notre équipe RH de 12 personnes la puissance d'une équipe de 40. Le copilote IA répond à 80% des questions des employés avant même qu'elles ne nous parviennent.", name: "Elena Moreau", role: "VP People · Northwind" },
      { initials: "RC", color: "#2DD4BF", textColor: "#fff", quote: "L'intégration prenait deux semaines de coordination. Aujourd'hui, c'est un seul fil automatisé qui se déroule tout seul. C'est presque magique.", name: "Raj Chauhan", role: "Responsable RH · Vertex" },
      { initials: "AB", color: "#FBBF24", textColor: "#3a2600", quote: "L'analytique a détecté un risque d'attrition dans une équipe des semaines à l'avance. Nous avons agi et gardé trois ingénieurs brillants. LOOM s'est rentabilisé plusieurs fois.", name: "Amara Bello", role: "DRH · Lumen" },
    ],
  },
  pricing: {
    eyebrow: "Tarifs",
    heading: ["Des offres simples qui grandissent", "avec votre équipe."],
    lead: "Par employé, par mois. Sans frais cachés. Annulable à tout moment.",
    plans: [
      {
        tier: "Starter",
        amount: "6 €",
        unit: "/employé/mois",
        desc: "Pour les équipes en croissance qui automatisent leurs RH.",
        features: [
          "Gestion des employés & annuaire",
          "Suivi des congés & de la présence",
          "Parcours d'intégration intelligents",
          "Copilote IA de base",
        ],
        cta: "Essai gratuit",
        ctaClass: "btn-glass",
      },
      {
        tier: "Growth",
        amount: "12 €",
        unit: "/employé/mois",
        desc: "Pour les entreprises qui font grandir leurs RH avec l'IA.",
        features: [
          "Tout ce qui est inclus dans Starter",
          "Copilote LLM complet & génération de documents",
          "Paie & évaluation de la performance",
          "Analytique et workflows avancés",
          "Gestion de la formation",
        ],
        cta: "Demander une démo",
        ctaClass: "btn-primary",
        featured: true,
        badge: "Le plus populaire",
      },
      {
        tier: "Enterprise",
        amount: "Sur mesure",
        desc: "Pour les organisations internationales aux besoins avancés.",
        features: [
          "Tout ce qui est inclus dans Growth",
          "SSO, SCIM & sécurité avancée",
          "Modèles IA sur mesure & résidence des données",
          "Chargé de succès client dédié",
        ],
        cta: "Contacter les ventes",
        ctaClass: "btn-glass",
      },
    ],
  },
  faq: {
    eyebrow: "FAQ",
    heading: "Vos questions, nos réponses.",
    items: [
      { q: "Comment fonctionne le copilote IA de LOOM ?", a: "Le copilote s'appuie sur de grands modèles de langage qui comprennent, en toute sécurité, les politiques, documents et données de votre entreprise. Il répond aux questions, rédige des documents RH, résume les réunions et recommande des actions — en conversation naturelle, sans que vos données servent jamais à entraîner des modèles publics." },
      { q: "Combien de temps faut-il pour démarrer ?", a: "La plupart des équipes sont opérationnelles en quelques jours. LOOM importe vos données collaborateurs existantes, et nos parcours d'intégration intelligents configurent automatiquement les modules principaux. Les déploiements Enterprise avec intégrations sur mesure prennent généralement 2 à 4 semaines." },
      { q: "Mes données collaborateurs sont-elles sécurisées ?", a: "Oui. LOOM utilise un chiffrement de niveau entreprise en transit et au repos, des accès basés sur les rôles, le SSO, la journalisation d'audit, et est conforme SOC 2 et RGPD. Vous contrôlez la résidence des données avec les offres Enterprise." },
      { q: "LOOM peut-il remplacer nos outils RH actuels ?", a: "LOOM regroupe gestion des employés, recrutement, intégration, congés, présence, paie, performance, formation, analytique, workflows et documents en une seule plateforme — remplaçant la plupart des outils spécialisés tout en s'intégrant à ceux que vous gardez." },
      { q: "Vous intégrez-vous à nos outils existants ?", a: "LOOM se connecte à Slack, Google Workspace, Microsoft 365, aux principaux prestataires de paie, aux outils ATS et bien plus, via des intégrations natives et une API ouverte." },
      { q: "Quels tarifs pour les grandes équipes ?", a: "L'offre Growth est facturée par employé et par mois. Pour les organisations de plus de 500 employés, nous proposons une offre Enterprise sur mesure avec remises sur volume, support dédié et sécurité avancée — contactez notre équipe pour un devis." },
    ],
  },
  forms: {
    eyebrow: "Commencer",
    heading: ["Tissons LOOM", "avec votre équipe."],
    lead: "Parlez-nous un peu de votre entreprise et nous adapterons la présentation — ou écrivez-nous simplement un mot. Une vraie personne (épaulée par l'IA, bien sûr) vous répond sous un jour ouvré.",
    points: [
      { title: "Démo personnalisée de 20 minutes", desc: "Découvrez LOOM et le copilote IA sur vos cas d'usage réels." },
      { title: "Estimation de ROI sur mesure", desc: "Nous modélisons le temps et les coûts que LOOM fait économiser à votre équipe." },
      { title: "Sans pression, sans spam", desc: "Juste des réponses utiles pour savoir si LOOM vous convient." },
    ],
    email: "hello@loom.hr",
    phone: "+33 1 76 54 00 00",
    tabs: { demo: "Demander une démo", contact: "Contacter les ventes" },
    demoForm: {
      firstName: "Prénom",
      lastName: "Nom",
      workEmail: "E-mail professionnel",
      company: "Entreprise",
      companySize: "Taille de l'entreprise",
      companySizeOptions: ["1–50", "51–200", "201–500", "501–1 000", "1 000+"],
      role: "Fonction",
      roleOptions: ["RH / People", "Fondateur / CEO", "Opérations", "IT / Sécurité", "Autre"],
      whatToSee: "Que souhaitez-vous voir ?",
      whatToSeePlaceholder: "ex. intégration IA, paie, analytique…",
      submit: "Réserver ma démo",
      consentPre: "En soumettant ce formulaire, vous acceptez la ",
      consentLink: "politique de confidentialité",
      consentPost: " de LOOM. Nous ne partagerons jamais vos données.",
      placeholders: { firstName: "Maya", lastName: "Anders", email: "maya@entreprise.com", company: "Nom de l'entreprise" },
    },
    contactForm: {
      fullName: "Nom complet",
      workEmail: "E-mail professionnel",
      topic: "Sujet",
      topicOptions: ["Tarifs Enterprise", "Sécurité & conformité", "Intégrations", "Partenariats", "Autre chose"],
      howCanWeHelp: "Comment pouvons-nous vous aider ?",
      howCanWeHelpPlaceholder: "Dites-nous ce que vous recherchez…",
      submit: "Envoyer le message",
      consent: "Nous répondons généralement sous un jour ouvré.",
      placeholders: { fullName: "Maya Anders", email: "maya@entreprise.com" },
    },
    success: {
      title: "Merci — c'est tout bon.",
      text: "Nous avons bien reçu votre demande. Un spécialiste LOOM vous contactera sous un jour ouvré.",
    },
  },
  cta: {
    heading: ["Prêt à tisser l'IA", "dans votre équipe RH ?"],
    text: "Rejoignez les entreprises qui construisent un lieu de travail plus intelligent et plus humain avec LOOM. Découvrez-le en direct lors d'une démo de 20 minutes.",
    primary: "Demander une démo",
    secondary: "Essai gratuit",
  },
  footer: {
    description: "La plateforme RH augmentée par l'IA où l'expertise humaine et les grands modèles de langage ne font plus qu'un.",
    columns: [
      { header: "Plateforme", links: [{ label: "Fonctionnalités", href: "#features" }, { label: "Copilote IA", href: "#ai" }, { label: "Tarifs", href: "#pricing" }, { label: "Cycle de vie", href: "#lifecycle" }] },
      { header: "Entreprise", links: [{ label: "À propos", href: "#" }, { label: "Carrières", href: "#" }, { label: "Clients", href: "#" }, { label: "Blog", href: "#" }] },
      { header: "Ressources", links: [{ label: "Centre d'aide", href: "#faq" }, { label: "Sécurité", href: "#" }, { label: "Confidentialité", href: "#" }, { label: "Statut", href: "#" }] },
    ],
    copyright: "© 2026 LOOM Technologies. Tous droits réservés.",
  },
  showcase: {
    eyebrow: "Une seule plateforme",
    heading: ["Le centre de contrôle de", "toute votre organisation."],
    lead: "Du premier entretien à l'au revoir, LOOM garde chaque dossier, workflow et conversation tissés ensemble — sur n'importe quel appareil.",
    points: [
      { title: "Annuaire collaborateurs en direct", desc: "Organigrammes, profils et documents qui se mettent à jour tout seuls." },
      { title: "Libre-service pour tous", desc: "Les employés demandent leurs congés, mettent à jour leurs infos et trouvent des réponses sans ticket." },
      { title: "Workflows en pilote automatique", desc: "Déclenchez validations, signatures électroniques et rappels entre équipes instantanément." },
      { title: "Pensé mobile avant tout", desc: "Validez, consultez et échangez avec le copilote IA depuis votre poche." },
    ],
    cta: "Explorer la plateforme",
    phone: {
      greeting: "Bonjour Maya 👋",
      dayLabel: "Votre journée",
      approvalsTag: "3 VALIDATIONS",
      approvalsText: "En attente de votre avis",
      paydayTag: "PAIE",
      paydayText: "Dans 4 jours",
      askAi: "Demandez au copilote IA…",
    },
  },
  dashboardMock: {
    url: "app.loom.hr / tableau-de-bord",
    nav: ["Tableau de bord", "Collaborateurs", "Paie", "Analytique", "Copilote IA"],
    greeting: "Bonjour Maya 👋",
    quarter: "Ce trimestre ▾",
    kpis: [
      { label: "Effectif", value: "1 284", trend: "▲ 4,1% sur le mois" },
      { label: "eNPS", value: "72", trend: "▲ 9 pts" },
      { label: "Postes ouverts", value: "37", trend: "▼ 6 vs sem. dern." },
    ],
    hiringVelocity: "Vitesse de recrutement",
    timeOffRequests: "Demandes de congés",
    people: [
      { initials: "AK", color: "#7C3AED", name: "Aria Khan", sub: "Vacances · 3j", badge: "Validé", badgeClass: "green" },
      { initials: "JL", color: "#2DD4BF", name: "Jon Lee", sub: "Maladie · 1j", badge: "Validé", badgeClass: "green" },
      { initials: "RP", color: "#FBBF24", textColor: "#3a2600", name: "Ravi Patel", sub: "Parental · 12sem", badge: "En attente", badgeClass: "amber" },
    ],
  },
  langSwitcher: { fr: "FR", en: "EN" },
};

export default fr;
